# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Set up NPM to install global packages without sudo
          command: >-
            wget -O- https://raw.githubusercontent.com/glenpike/npm-g_nosudo/master/npm-g-nosudo.sh | sh \
            export NPM_PACKAGES="/home/circleci/.npm-packages" \
            export NODE_PATH="$NPM_PACKAGES/lib/node_modules${NODE_PATH:+:$NODE_PATH}" \
            export PATH="$NPM_PACKAGES/bin:$PATH" \
            unset MANPATH \
            export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"
          # see https://github.com/glenpike/npm-g_nosudo
          # see https://github.com/trufflesuite/truffle/issues/1212

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install global packages (without sudo)
          command: npm install -g truffle codecov greenkeeper-lockfile@1

      # - run:
      #     name: Greenkeeper Lockfile
      #     command: greenkeeper-lockfile-update

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Solidity Linter
          command: npm run lint:sol

      - run:
          name: Javascript Linter
          command: npm run lint:js

      # disabled until solidity-coverage supports truffle 5.
      # see https://github.com/sc-forks/solidity-coverage/pull/311
      # - run:
      #     name: Unit tests with code coverage
      #     command: npm run test:cov

      - run:
          name: Unit tests
          command: npm test

      # - run:
      #     name: Push any lockfile changes
      #     command: greenkeeper-lockfile-upload

      # as per comments above.
      # - run:
      #     name: Send reports to codecov.io
      #     command: codecov
